#!/bin/bash
set -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
    django-admin collectstatic --settings=kgreg.conf.settings --noinput
fi

if [ "$1" = "triggered" ]; then
    if [ "$2" = "karaage-migrations" ]; then
        echo "Running migrations"
        django-admin migrate --settings=kgreg.conf.settings --noinput
    fi
fi
